version: "3"
services: 
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/backend/src
